apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - image: hyasuhisa/spring-petclinic-visits-service:c53f193561c7631f6e7dde485b8ccbfdbef9d5f3
        name: visits-service
        ports:
        - containerPort: 8082
