apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - image: hyasuhisa/spring-petclinic-discovery-server:c53f193561c7631f6e7dde485b8ccbfdbef9d5f3
        name: discovery-server
        ports:
        - containerPort: 8761
