apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - image: hyasuhisa/spring-petclinic-config-server:c53f193561c7631f6e7dde485b8ccbfdbef9d5f3
        name: config-server
        ports:
        - containerPort: 8888
